version: 2
jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:2.6.6
    steps:
      - checkout
      - run:
          name: Install CMake, pkg-config and system dependencies
          command: sudo apt update && sudo apt install cmake pkg-config libsqlite3-dev
      - run:
          name: Install Bundler
          command: |
            sudo gem update --system
            gem install bundler --no-document
      - run:
          name: Install dependencies (bundler)
          command: |
            bundle config set frozen 'true'
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4
      - run:
          name: Install linting dependencies (Bundler)
          command: |
            bundle config set frozen 'true'
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4
      - run:
          name: Lint Ruby sources (RSpec)
          command: bundle exec rspec

  lint-ruby:
    docker:
      - image: cimg/ruby:2.6.6
    steps:
      - checkout
      - run:
          name: Install CMake, pkg-config and system dependencies
          command: sudo apt update && sudo apt install cmake pkg-config libsqlite3-dev
      - run:
          name: Install Bundler
          command: |
            sudo gem update --system
            gem install bundler --no-document
      - run:
          name: Install dependencies (bundler)
          command: |
            bundle config set frozen 'true'
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4
      - run:
          name: Lint Ruby sources (Rubocop)
          command: bundle exec rubocop

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-ruby:
          context: default
      - lint-ruby:
          context: default
