version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout

      - run:
          name: "Creating a Gemfile.lock without bundler's version"
          command: "head -n -3 Gemfile.lock > Gemfile.lock.no-version"

      # Bundle install with cache, Ignore bundler version
      - restore_cache:
          key: checker_jobs-{{ checksum "Gemfile.lock.no-version"}}
      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle --jobs=`nproc`
      - save_cache:
          key: checker_jobs-{{ checksum "Gemfile.lock.no-version"}}
          paths:
            - vendor/bundle

      - run:
          name: RSpec
          command: bundle exec rspec --format documentation

